### ISSUE TITLE
Redis message persistance

### ISSUE THREAD

**Issue by anarthal** [anarthal/servertech-chat#19]
When the Redis container is deleted and re-created in AWS, messages are lost. Place them in a volume so this doesn't happen.

Redis persistence is by default configured to just use RDB, which doesn't provide enough durability. Redis docs suggest that enabling AOF with the default settings should get us the desired performance/durability tradeoff.

**Comment by RoyBellingan** [comment]
Are we sure redis is the best place to keep the message ? the max message that we can store is bound to the memory of the instance, I would suggest to evaluate the usage of mysql / mariadb to store those data.

**Comment by mzimbres** [comment]
Only hot data will be kept in Redis, for example the recent history of each chat root that will be request by all new joiners. All data either hot or cold will have to be offloaded into MySql, but that is independent of Redis.

**Comment by anarthal** [comment]
I'm not following you here - what do you mean by "hot data" and "cold data"?

I've double-checked Redis default persistence settings and it does a write-to-disk every while (it depends on the number of writes, something between 5min and 1h). My plan is enabling persistence by append-only-file, which according to [this](https://redis.io/docs/management/persistence/) provides the kind of durability/performance tradeoff we need.

I'd still offload old messages to mysql to keep Redis as light as possible (see #24).

**Comment by mzimbres** [comment]
> I'm not following you here - what do you mean by "hot data" and "cold data"?

Hot is referring to data that is frequently needed.

> I've double-checked Redis default persistence settings and it does a
> write-to-disk every while (it depends on the number of writes,
> something between 5min and 1h).

Yes, this can be adjusted in the redis config file e.g. write every 2s if there was at least one write operation.

> My plan is enabling persistence by append-only-file, which according
> to this provides the kind of durability/performance tradeoff we
> need.
>
> I'd still offload old messages to mysql to keep Redis as light as
> possible (see #24).

Ok, this looks safe. I though we would be using RDB file format with important data being writen in MySql right away. But I think this would make it dificult to handle redis crashes than just using an AOF file.
