### ISSUE TITLE
MySQL connection pool

### ISSUE THREAD

**Issue by anarthal** [anarthal/servertech-chat#48]
Currently, we're creating, connecting, closing and destroying a MySQL connection for every request. This is inefficient. A connection pool can be much more efficient.

**Comment by RoyBellingan** [comment]
I have always used a queue with mutex to protect the push pop.

What about something like this ?

//on scope exit will put back in the queue
QueueHandler something(queue); //this will internall call .pop, and if empty will create and connect new one

something.dbHandler->query ecc

I still have to wrap my head around the async world, but from seeing boost.redis example... is more or less viable to handle the handler like that.

As you described a potential blocking operation is in case we have to perform the dns name resolution, but is conceptually similar to what boost.redis does in

 auto conn = std::make_shared<connection>(co_await net::this_coro::executor);
   conn->async_run(cfg, {}, net::consign(net::detached, conn));


just we do inside.

?
